In [1]:
import numpy as np

In [2]:
np_array = np.array([1,2,3])
print(np_array *5 )

[ 5 10 15]


In [5]:
# two dimensional array with zeros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(2, 20, 5)

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [8]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
a= np.array([[1,2,3],
            [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr= np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
arr.shape

(9,)